[build]
publish = "public"
command = "hugo --gc --minify"
#command = "hugo --gc --minify --baseURL"

[context.production.environment]
HUGO_VERSION = "0.101.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"