name = "Compose"
license = "MIT"
licenselink = "https://github.com/onweru/compose/blob/master/LICENSE"
description = "A hugo theme for documentation sites. It's inspired by forestry.io's guias page"
homepage = "https://guias.neuralvibes.com"
tags = ["dark mode", "guias", "dark", "blog", "search", "documentation"]
features = ["dark mode", "guias", "dark", "blog", "search", "documentation"]
min_version = "0.76.0"

[author]
  name = "Weru"
  homepage = "https://github.com/onweru"
