# use the setting below to set multiple guias directories.
# guiasections = ["guias", "tutorials", "guias"]

uniqueHomePage = true # change to false to add sidebar to homepage

repo = "https://github.com/sapienstj/wiki"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# Site logo
[logo]
  lightMode = "images/compose.svg"
  darkMode = "images/compose-light.svg"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/sapienstj/wiki/"

# optional
# attribution. Feel free to delete this
[author]
  name = "Feito com <3"
  url = "https://instagram.com/eubaliver/"
